import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../server.mjs';
import {normalize,searchRank,searchConditions,calculateMatchScore} from '../backend/case-search.mjs';
import {caseMatches,comparisonBackLink} from '../frontend/js/components/case-matches.js';
import {detail} from '../frontend/js/pages/detail.js';
import {filters,petCard} from '../frontend/js/components/ui.js';

const sample={name:'Luna',species:'Perro',breed:'Labrador',color:'Negro',sex:'Hembra',size:'Mediano',city:'Bogotá',zone:'Chapinero',description:'Collar violeta y cicatriz izquierda',kind:'lost',state:'open',created:'2026-09-17T12:00:00.000Z'};
test('Coincidencias: señales reales, incompatibilidades, ausencias y fechas de publicación',()=>{
  const found={...sample,kind:'found'};
  const match=calculateMatchScore(sample,found);assert.equal(match.score,100);assert.ok(match.reasons.includes('Misma zona indicada'));
  assert.equal(calculateMatchScore(sample,{...found,species:'Gato'}).score,0);
  assert.equal(calculateMatchScore(sample,{...found,sex:'Macho'}).score,0);
  assert.equal(calculateMatchScore(sample,{...found,kind:'lost'}).score,0);
  assert.equal(calculateMatchScore(sample,{...found,state:'resolved'}).score,0);
  const otherColor=calculateMatchScore(sample,{...found,color:'Blanco'});assert.ok(otherColor.score<match.score);assert.ok(!otherColor.reasons.includes('Color en común'));
  const otherCity=calculateMatchScore(sample,{...found,city:'Cali'});assert.ok(otherCity.score<match.score);assert.ok(!otherCity.reasons.includes('Misma zona indicada'));
  assert.ok(calculateMatchScore(sample,{...found,zone:'Centro'}).score<match.score);
  assert.ok(calculateMatchScore(sample,{...found,created:'2025-01-01'}).score<match.score);
  // Un encontrado publicado antes del perdido no demuestra una cronología imposible.
  assert.ok(calculateMatchScore(sample,{...found,created:'2026-09-16'}).score>0);
  assert.equal(calculateMatchScore({},{}).score,0);
  assert.equal(calculateMatchScore(sample,{kind:'found',state:'open',species:'Perro',city:'Bogotá',created:sample.created}).score,0);
  assert.equal(calculateMatchScore({...sample,species:'Otro'},{...found,species:'Otro'}).score,0);
  assert.ok(calculateMatchScore(sample,{...found,created:undefined}).reasons.every(reason=>!reason.startsWith('Publicados')));
});
test('Búsqueda: acentos, espacios, términos repartidos, literales y día de Colombia',()=>{
  assert.equal(normalize('  BOGOTÁ   café '),'bogota cafe');
  assert.ok(searchRank(sample,'  NEGRO   bogota cicatriz ')>0);
  assert.ok(searchRank(sample,'labrador')>0);
  assert.equal(searchRank(sample,'%'),0);assert.equal(searchRank(sample,'negro ausente'),0);
  assert.equal(searchRank({},'gato'),0);
  const date=searchConditions(new URLSearchParams('period=today'),Date.parse('2026-09-17T03:00:00Z'));
  assert.deepEqual(date.args,['2026-09-16T05:00:00.000Z','2026-09-17T03:00:00.000Z']);
});
test('API de búsqueda y coincidencias: filtros combinados, orden, páginas y privacidad',async t=>{
  const dir=mkdtempSync(join(tmpdir(),'buscados-search-')),server=createApp({dataDir:dir});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const db=new DatabaseSync(join(dir,'buscados.sqlite'));
  t.after(async()=>{db.close();await new Promise(resolve=>server.close(resolve));rmSync(dir,{recursive:true,force:true});});
  const base='http://127.0.0.1:'+server.address().port+'/api/v1';
  const now=Date.now(),created=delta=>new Date(now-delta*86400000).toISOString();
  db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run('owner','Ana','search@example.test','unused','USER');
  const insert=(id,kind,changes={},age=0,state='open')=>db.prepare('INSERT INTO cases VALUES(?,?,?,?,?,?)').run(id,'owner',kind,state,JSON.stringify({...sample,...changes}),created(age));
  insert('source','lost');
  for(let i=0;i<7;i++)insert('similar-'+i,'found',{},i);
  insert('cat','found',{species:'Gato'});insert('white','found',{color:'Blanco',breed:'',description:'Sin datos adicionales'});
  insert('far','found',{city:'Cali',zone:'Centro'},35);insert('resolved','found',{},0,'resolved');insert('hidden','found');
  insert('adoption','adoption',{},0,'available');
  db.prepare('INSERT INTO moderation VALUES(?,?,?,?)').run('hidden','hidden','motivo privado',created(0));
  const get=async path=>{const response=await fetch(base+path);assert.equal(response.status,200);return response.json();};
  const query='/cases?kind=found&species=perro&sex=hembra&size=mediano&color=negro&city=bogota&zone=chapinero&period=7&state=open&q=collar';
  const first=await get(query+'&limit=3');assert.equal(first.total,7);assert.equal(first.items.length,3);
  const second=await get(query+'&limit=3&offset=3');assert.ok(second.items.every(item=>!first.items.some(previous=>previous.id===item.id)));
  const oldest=await get(query+'&sort=oldest&limit=1');assert.equal(oldest.items[0].id,'similar-6');
  const relevant=await get(query+'&sort=relevance&limit=1');assert.equal(relevant.items[0].id,'similar-0');
  assert.equal((await get('/cases?q=NOEXISTE')).total,0);
  assert.equal((await get('/cases?q=%25')).total,0);
  assert.equal((await get('/cases?species=Gato')).total,1);
  assert.equal((await get('/cases?color=Blanco&species=Perro')).total,1);
  const matches=await get('/cases/source/matches');assert.equal(matches.items.length,5);assert.equal(matches.items[0].id,'similar-0');
  for(const item of matches.items){assert.equal(item.kind,'found');assert.equal(item.image,'');assert.ok(item.matchReasons.includes('Misma especie'));assert.equal(item.owner_id,undefined);assert.equal(item.score,undefined);}
  assert.ok((await get('/cases/similar-0/matches')).items.some(item=>item.id==='source'));
  assert.deepEqual((await get('/cases/cat/matches')).items,[]);
  assert.deepEqual((await get('/cases/resolved/matches')).items,[]);
  assert.deepEqual((await get('/cases/adoption/matches')).items,[]);
  assert.equal((await fetch(base+'/cases/hidden/matches')).status,404);
  assert.equal((await fetch(base+'/cases/missing/matches')).status,404);
  // No se sirve una coincidencia cacheada tras ocultar o resolver el destino.
  db.prepare("UPDATE cases SET state='resolved' WHERE id='similar-0'").run();
  assert.ok((await get('/cases/source/matches')).items.every(item=>item.id!=='similar-0'));
  assert.ok((await get('/cases')).total>first.total);
});
test('Vista: motivos escapados, sin foto, enlace al detalle y estados vacíos o de error',async t=>{
  const original=globalThis.fetch,originalLocation=globalThis.location;t.after(()=>{globalThis.fetch=original;globalThis.location=originalLocation;});
  const item={...sample,id:'candidate',kind:'found',status:'Encontrado',matchReasons:['Color <script>similar</script>']};
  globalThis.fetch=async()=>({ok:true,json:async()=>({items:[item]})});
  const html=await caseMatches({...sample,id:'source'});
  assert.match(html,/Posibles coincidencias/);assert.match(html,/#\/mascota\/candidate/);assert.match(html,/Sin fotografía/);assert.ok(!html.includes('<script>'));
  assert.match(html,/#\/mascota\/candidate\?from=source/);
  const target=html.match(/href="(#\/mascota\/candidate[^\"]*)"/)[1];
  globalThis.location={hash:target};
  globalThis.fetch=async path=>({ok:true,json:async()=>path.endsWith('/matches')?{items:[]}:{...item,photos:[]}});
  const candidateDetail=await detail('candidate');assert.match(candidateDetail,/href="#\/mascota\/source">← Volver al reporte original/);
  assert.equal(comparisonBackLink('#/mascota/candidate?from=https://evil.test'),'');
  assert.equal(comparisonBackLink('#/mascota/candidate?from=%22%3E%3Cscript%3E'),'');
  assert.match(html,/no confirma que sea el mismo animal/);assert.match(html,/#\/encontrados\?state=open/);
  globalThis.fetch=async()=>({ok:true,json:async()=>({items:[]})});assert.match(await caseMatches({...sample,id:'source'}),/No encontramos coincidencias claras/);
  globalThis.fetch=async()=>{throw Error('offline');};assert.match(await caseMatches({...sample,id:'source'}),/No pudimos consultar/);
  assert.equal(await caseMatches({...sample,state:'resolved'}),'');
  assert.match(filters(),/data-clear-filters/);assert.match(filters(),/aria-live="polite"/);assert.match(filters(),/Fecha de publicación/);
  assert.ok(!filters('lost').includes('data-case-filter="kind"'));assert.ok(!filters('adoption').includes('data-case-filter="state"'));
  assert.match(petCard({...sample,id:'x',color:'Negro <script>'}),/Negro &lt;script&gt;/);
});
