import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../server.mjs';
import {grantAdmin} from '../scripts/admin.mjs';

test('Flujo completo: contacto vinculado, respuesta, resolución autorizada e historial persistente',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'buscados-followup-'));let server,base;
 const start=async()=>{server=createApp({dataDir:dir});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port+'/api/v1';};
 const stop=()=>new Promise(r=>server.close(r));
 t.after(async()=>{if(server?.listening)await stop();rmSync(dir,{recursive:true,force:true});});
 const call=(path,method='GET',body,cookie)=>fetch(base+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const get=async(path,cookie)=>{const r=await call(path,'GET',null,cookie);assert.equal(r.status,200);return r.json();};
 const register=async email=>{const r=await call('/register','POST',{email,name:email.split('@')[0],password:'Test-only-123'});return r.headers.get('set-cookie').split(';')[0];};
 await start();const a=await register('Ana@example.com'),b=await register('Beto@example.com'),other=await register('Other@example.com');
 const body={name:'Luna',species:'Perro',city:'Bogotá',zone:'Centro',description:'Collar violeta cicatriz izquierda',color:'Negro',sex:'Hembra',breed:'Labrador'};
 const lost=await (await call('/cases','POST',{...body,kind:'lost',email:'private@example.test',phone:'123456789'},a)).json();
 const found=await (await call('/cases','POST',{...body,kind:'found'},b)).json();
 assert.equal(lost.email,undefined);assert.equal(lost.phone,undefined);assert.equal(lost.canResolve,true);
 assert.ok((await get('/cases/'+lost.id+'/matches')).items.some(p=>p.id===found.id));
 const path='/cases/'+lost.id+'/conversations',open={openOnly:true,relatedCaseId:found.id};
 assert.equal((await call(path,'POST',open)).status,401);
 assert.equal((await call(path,'POST',open,a)).status,400);
 assert.equal((await call(path,'POST',{...open,relatedCaseId:'bad/id'},b)).status,400);
 assert.equal((await call('/cases/%3Cbad%3E/conversations','POST',open,b)).status,400);
 assert.equal((await call(path,'POST',{...open,relatedCaseId:randomUUID()},b)).status,404);
 assert.equal((await call(path,'POST',{...open,relatedCaseId:lost.id},b)).status,400);
 const opened=await Promise.all([call(path,'POST',open,b),call(path,'POST',open,b)]);
 assert.deepEqual(opened.map(r=>r.status).sort(),[200,201]);const ids=await Promise.all(opened.map(r=>r.json()));assert.equal(ids[0].id,ids[1].id);
 const thread='/conversations/'+ids[0].id;
 const reverse=await call('/cases/'+found.id+'/conversations','POST',{openOnly:true,relatedCaseId:lost.id},a);assert.equal(reverse.status,200);assert.equal((await reverse.json()).id,ids[0].id);
 const initial=await get(thread,b);assert.equal(initial.items.length,0);assert.equal(initial.cases.length,2);assert.ok(initial.cases.every(p=>p.available));
 assert.equal((await get('/conversations',a)).total,1);
 // Un hilo antiguo sin vínculo en el sentido opuesto no debe sustituir la combinación ya vinculada.
 const legacyDb=new DatabaseSync(join(dir,'buscados.sqlite'));
 const aId=legacyDb.prepare('SELECT owner_id FROM cases WHERE id=?').get(lost.id).owner_id,bId=legacyDb.prepare('SELECT owner_id FROM cases WHERE id=?').get(found.id).owner_id;
 legacyDb.prepare('INSERT INTO conversations(id,case_id,owner_id,visitor_id,created) VALUES(?,?,?,?,?)').run('legacy-thread',found.id,bId,aId,new Date().toISOString());
 const legacyLookup=await call('/cases/'+found.id+'/conversations','POST',{openOnly:true,relatedCaseId:lost.id},a);assert.equal((await legacyLookup.json()).id,ids[0].id);
 legacyDb.prepare("DELETE FROM conversations WHERE id='legacy-thread'").run();legacyDb.close();
 assert.equal((await call(thread,'GET',null,other)).status,404);
 assert.equal((await call(thread+'/messages','POST',{text:'  ',clientId:randomUUID()},b)).status,400);
 assert.equal((await call(thread+'/messages','POST',{text:'Hola',clientId:'bad'},b)).status,400);
 assert.equal((await call('/conversations/%3Cbad%3E','GET',null,b)).status,400);
 const first={text:'Encontré una perrita muy parecida <script>',clientId:randomUUID()};
 assert.equal((await call(thread+'/messages','POST',first,b)).status,201);
 assert.equal((await call(thread+'/messages','POST',first,b)).status,200);
 assert.equal((await get(thread,a)).items[0].text,first.text);
 assert.equal((await call(thread+'/messages','POST',{text:'Gracias, verifiquemos las características.',clientId:randomUUID()},a)).status,201);
 assert.equal((await get(thread,b)).items.length,2);
 const inbox=(await get('/conversations',b)).items[0];assert.match(inbox.lastText,/Gracias/);assert.ok(inbox.lastCreated);assert.equal(inbox.unread,1);
 const resolved={state:'resolved',resolution:{outcome:'reunited',note:'Luna volvió con su familia. <script>',resolvedAt:'1900-01-01'}};
 assert.equal((await call('/cases/'+lost.id,'PATCH',resolved,b)).status,403);
 assert.equal((await call('/cases/'+lost.id,'PATCH',resolved)).status,401);
 assert.equal((await call('/cases/'+lost.id,'PATCH',{...resolved,resolution:{outcome:'invalid',note:''}},a)).status,400);
 assert.equal((await call('/cases/'+lost.id,'PATCH',{...resolved,resolution:{outcome:'safe',note:'x'.repeat(301)}},a)).status,400);
 const result=await call('/cases/'+lost.id,'PATCH',resolved,a);assert.equal(result.status,200);const pet=await result.json();assert.equal(pet.status,'Resuelto');assert.equal(pet.resolution.note,resolved.resolution.note);assert.notEqual(pet.resolution.resolvedAt,'1900-01-01');
 const repeated=await (await call('/cases/'+lost.id,'PATCH',resolved,a)).json();assert.deepEqual(repeated.resolution,pet.resolution);
 assert.equal((await call('/cases/'+lost.id,'PATCH',{...resolved,resolution:{outcome:'safe',note:'Otro'}},a)).status,409);
 assert.ok(!(await get('/cases/'+found.id+'/matches')).items.some(p=>p.id===lost.id));
 assert.ok((await get('/cases?mine=true&state=resolved',a)).items.some(p=>p.id===lost.id));
 assert.equal((await get('/cases?sort=oldest')).items[0].id,found.id);
 assert.equal((await call(path,'POST',{openOnly:true},other)).status,409);
 assert.equal((await call(path,'POST',open,b)).status,200);
 assert.equal((await call(thread+'/messages','POST',{text:'Gracias por el reencuentro.',clientId:randomUUID()},b)).status,201);
 // Una edición ordinaria conserva el resultado y su fecha originales.
 const edited=await (await call('/cases/'+lost.id,'PATCH',{description:'Actualización posterior'},a)).json();assert.deepEqual(edited.resolution,pet.resolution);
 grantAdmin(join(dir,'buscados.sqlite'),'other@example.com');const login=await call('/login','POST',{email:'other@example.com',password:'Test-only-123'});const admin=login.headers.get('set-cookie').split(';')[0];
 assert.equal((await call(thread,'GET',null,admin)).status,404);
 assert.equal((await call('/cases/'+lost.id,'PATCH',{state:'open'},admin)).status,403);
 assert.equal((await get('/cases/'+lost.id,admin)).canResolve,false);
 assert.equal((await call('/admin/cases/'+found.id+'/moderation','PATCH',{visibility:'hidden',reason:'Revisión de contenido'},admin)).status,200);
 const hidden=(await get(thread,a)).cases.find(p=>p.id===found.id);assert.deepEqual(hidden,{id:found.id,available:false});
 assert.equal((await call(path,'POST',open,b)).status,404);
 await stop();await start();
 assert.equal((await get(thread,b)).items.length,3);assert.equal((await get(thread,b)).cases.length,2);assert.equal((await get('/cases/'+lost.id)).resolution.outcome,'reunited');
 assert.equal((await call('/cases/'+lost.id,'PATCH',{state:'open'},a)).status,200);assert.equal((await get('/cases/'+lost.id)).resolution,undefined);
 const db=new DatabaseSync(join(dir,'buscados.sqlite'));assert.equal(db.prepare('SELECT count(*) AS n FROM conversations').get().n,1);assert.equal(db.prepare('SELECT count(*) AS n FROM conversation_cases').get().n,1);db.close();
});
