import {api} from '../services/api.js';
import {header,filters} from '../components/ui.js';
import {socialCase} from '../components/social.js';
import {icon} from '../components/icons.js';
export async function home(){
 const {items,total}=await api.listCases({limit:8});
 return `<header class="community-heading"><div><span class="eyebrow">Juntos, de vuelta a casa</span><h1>Tu comunidad</h1><p>Cada pista puede ser el comienzo de un reencuentro.</p></div><a class="heading-search" href="#/explorar" aria-label="Buscar una mascota">${icon('search')}</a></header><section class="card social-composer"><div class="composer-prompt"><span class="composer-paw">${icon('paw',25)}</span><button data-modal="lost">¿Nos ayudas a encontrar a alguien?</button><button class="compose-plus" data-modal="lost" aria-label="Crear reporte">${icon('plus')}</button></div><div class="composer-choices"><button data-modal="lost">${icon('pin',19)}Reportar perdido</button><span></span><button data-modal="found">${icon('heart',19)}Encontré una mascota</button></div></section><nav class="feed-tabs" aria-label="Filtrar casos"><a class="active" href="#/inicio">Recientes</a><a href="#/perdidos">Perdidos</a><a href="#/encontrados">Encontrados</a></nav><div class="feed-caption"><h2>Reportes recientes</h2><span>${total} casos publicados</span></div><div class="social-feed">${items.map(socialCase).join('')}</div>${!total?`<section class="card social-empty"><div class="empty-paw">${icon('paw',58)}<span>${icon('heart',20)}</span></div><span class="eyebrow">La comunidad empieza contigo</span><h2>Un pequeño gesto.<br>Una gran posibilidad de volver.</h2><p>Aquí verás los reportes de mascotas perdidas y encontradas. Publica el primer caso para empezar a ayudar.</p><button class="button" data-modal="lost">${icon('plus',18)}Publicar un caso</button><a href="#/encontrados">Encontré una mascota ${icon('arrow',16)}</a></section>`:'<a class="feed-see-all button secondary" href="#/explorar">Explorar todos los casos →</a>'}`;
}
export async function listing(kind){
 if(kind==='adoption')return header('Un hogar para toda la vida','Adopciones responsables','Conoce los cuidados y requisitos antes de enviar una solicitud privada.', '<button class="button" data-modal="adoption">Publicar en adopción</button><a class="button secondary" href="#/solicitudes-adopcion">Mis solicitudes</a>')+filters('adoption')+`<div class="grid-list" data-live-cases data-kind="adoption"></div><p role="status" data-list-status></p><button class="button secondary" data-load-more hidden>Ver más mascotas</button>`;
 const lost=kind==='lost';
 return header('Cada pista cuenta',lost?'Mascotas perdidas':'Mascotas encontradas','Busca por nombre, especie o ubicación aproximada.',`<button class="button" data-modal="${kind}">${icon('plus',18)}${lost?'Reportar perdido':'Encontré una mascota'}</button>`)+filters(kind)+`<div class="grid-list" data-live-cases data-kind="${kind}"></div><p role="status" data-list-status></p><button class="button secondary" data-load-more hidden>Ver más casos</button>`;
}