/** Inicio y listados comunitarios. Reutilizan API, tarjetas, filtros y modal existentes. */
import {api} from "../services/api.js";import {header,petCard,postCard,filters} from "../components/ui.js";

export async function home(){const [posts,pets]=await Promise.all([api.getPosts(),api.getPets()]);return '<section class="home-hero card"><div class="home-hero-copy"><span class="eyebrow">Una comunidad que no deja de buscar</span><h1>Ayudamos a que los animales perdidos vuelvan a casa</h1><p>Una publicación clara, una fotografía y alguien que reconozca al animal pueden cambiar una historia. Cada ser vivo importa y cada búsqueda merece esperanza.</p><a class="button" href="#acciones-principales">Quiero ayudar</a></div><div class="home-hope" aria-label="Mensaje de esperanza"><strong>Seguir buscando sí importa</strong><span>Perros, gatos, aves, peces y cualquier otro animal pueden ser parte irremplazable de una familia.</span></div></section>'+priorityActions()+'<section class="urgent-strip"><div class="section-heading"><div><span class="eyebrow">Atención prioritaria</span><h2>Casos urgentes cerca de ti</h2></div><a href="#/perdidos">Ver todos</a></div><div class="urgent-grid">'+pets.slice(0,3).map(p=>'<a class="card urgent-card" href="#/mascota/'+p.id+'"><img src="'+p.image+'" alt="'+p.name+'"><div><span class="badge '+p.kind+'">'+p.status+'</span><h3>'+p.name+'</h3><span class="caption">'+p.zone+'<br>'+p.time+'</span></div></a>').join("")+'</div></section><section class="card composer"><div class="composer-row"><span class="avatar">VR</span><button class="composer-trigger" data-modal="post">¿Qué quieres compartir?</button></div><div class="composer-options"><button data-modal="post">Publicación</button><button data-modal="lost">Perdida</button><button data-modal="found">Encontrada</button></div></section><div class="feed">'+posts.map(postCard).join("")+'</div>'}

/** details/summary aporta apertura por teclado sin crear estado o listeners duplicados. */
function priorityActions(){return '<section id="acciones-principales" class="priority-section" aria-labelledby="priority-title"><div class="section-heading"><div><span class="eyebrow">Empieza aquí</span><h2 id="priority-title">¿Qué necesitas hacer?</h2></div><p>Primero elige el caso; después decide si quieres publicar o mirar.</p></div><div class="priority-menu"><details class="card priority-choice"><summary><span class="priority-symbol lost" aria-hidden="true">!</span><span><strong>Mascotas perdidas</strong><small>Perdí un animal o quiero ayudar a reconocerlo</small></span></summary><div class="priority-options"><button class="button danger" type="button" data-modal="lost">Publicar</button><a class="button secondary" href="#/perdidos">Mirar</a></div></details><details class="card priority-choice"><summary><span class="priority-symbol found" aria-hidden="true">✓</span><span><strong>Encontrados</strong><small>Encontré un animal o estoy buscando entre los hallazgos</small></span></summary><div class="priority-options"><button class="button" type="button" data-modal="found">Publicar</button><a class="button secondary" href="#/encontrados">Mirar</a></div></details></div></section>'}

export async function listing(kind){const labels={lost:["Animales perdidos","Ayuda a que vuelvan a casa","lost"],found:["Animales encontrados","Protegidos mientras buscamos a su familia","found"],adoption:["Adopciones responsables","Conoce animales que esperan un hogar comprometido","adoption"]};const [title,text,modal]=labels[kind];const pets=await api.getPets(kind);return header("Explorar casos",title,text,'<button class="button '+(kind==="lost"?"danger":"")+'" data-modal="'+modal+'">'+(kind==="lost"?"Reportar pérdida":kind==="found"?"Encontré un animal":"Publicar adopción")+'</button>')+filters(title.toLowerCase())+'<div class="grid-list" data-pet-grid>'+pets.map(petCard).join("")+'</div><div data-empty-results hidden><div class="card state-card"><h2>Sin resultados</h2><p>No encontramos casos con estos filtros.</p></div></div>'}
