import {api} from "../services/api.js";
import {header,statePage} from "../components/ui.js";
const icons={track:"◉",bird:"⌁",scale:"◇",drop:"◒",fish:"◁",wing:"⌘"};
const intentionalEmpty=(title,text,note="No se añadieron especies ni datos científicos ficticios.")=>'<section class="card structured-empty"><span class="empty-orbit" aria-hidden="true">○</span><div><span class="eyebrow">Estructura preparada</span><h2>'+title+'</h2><p>'+text+'</p><span class="structure-note">'+note+'</span></div></section>';
const classificationCard=item=>'<a class="card category-card navigable-card" data-content-card data-search="'+item.name.toLowerCase()+' '+item.description.toLowerCase()+'" href="#/informacion/'+item.slug+'"><span class="nature-icon" aria-hidden="true">'+icons[item.icon]+'</span><div><span class="eyebrow">Clasificación principal</span><h2>'+item.name+'</h2><p>'+item.description+'</p><strong>Explorar categorías →</strong></div></a>';
const categoryCard=(item,basePath)=>'<a class="card category-card navigable-card" href="#'+basePath+'/'+item.slug+'"><span class="nature-icon small" aria-hidden="true">'+icons[item.icon]+'</span><div><span class="eyebrow">Grupo de navegación</span><h2>'+item.name+'</h2><p>'+item.description+'</p><strong>Explorar este grupo →</strong></div></a>';
function breadcrumbs(classification,trail){const segments=['<a href="#/informacion">Información y cuidados</a>','<a href="#/informacion/'+classification.slug+'">'+classification.name+'</a>'];let path='#/informacion/'+classification.slug;for(const item of trail){path+='/'+item.slug;segments.push('<a href="'+path+'">'+item.name+'</a>')}return '<nav class="breadcrumbs" aria-label="Ruta de navegación">'+segments.map((item,index)=>index===segments.length-1?'<span aria-current="page">'+item.replace(/^<a[^>]*>|<\/a>$/g,"")+'</span>':item+'<b aria-hidden="true">›</b>').join("")+'</nav>'}

export async function uncommon(){const [classifications,collections]=await Promise.all([api.getClassifications(),api.getCollections()]);const uncommon=collections.find(item=>item.slug==="poco-comunes");return header("Descubrimiento editorial","Poco comunes","Una selección futura de organismos menos habituales. No es una clasificación taxonómica y nunca duplicará las fichas originales.",'<a class="button secondary" href="#/informacion">Explorar la biblioteca</a>')+'<section class="card editorial-explainer"><div><span class="eyebrow">Cómo funcionará</span><h2>Una colección que conecta, no una categoría que duplica</h2><p>Cada organismo tendrá una única ficha y una clasificación principal. Podrá aparecer aquí mediante una relación editorial.</p></div><div class="relation-map"><span>Ficha única</span><b>→</b><span>Clasificación</span><b>+</b><span>Colección</span></div></section>'+(uncommon?'<section class="collection-results"></section>':intentionalEmpty("Estamos preparando las primeras selecciones verificadas","Las colecciones editoriales relacionarán fichas reales cuando exista contenido aprobado.","0 colecciones publicadas · 0 especies duplicadas"))+'<section class="section-intro"><span class="eyebrow">Explorar por clasificación</span><h2>Seis rutas principales para llegar a las categorías</h2></section><div class="content-grid compact-categories">'+classifications.map(classificationCard).join("")+'</div>'}

export async function knowledge(){const [classifications,entries]=await Promise.all([api.getClassifications(),api.getKnowledgeEntries()]);return header("Biblioteca abierta","Información y cuidados","Explora clasificaciones y categorías preparadas para recibir fichas verificadas.")+'<section class="card library-tools"><div class="search"><label for="knowledge-search">Buscar en la estructura</label><input id="knowledge-search" class="input" data-content-search placeholder="Buscar clasificaciones" autocomplete="off"></div><div class="field"><label for="knowledge-filter">Clasificación</label><select id="knowledge-filter" class="select" data-content-filter><option value="">Todas las clasificaciones</option>'+classifications.map(c=>'<option value="'+c.name.toLowerCase()+'">'+c.name+'</option>').join("")+'</select></div></section><p class="caption" data-content-count>'+classifications.length+' clasificaciones visibles · '+entries.length+' fichas publicadas</p><div class="content-grid" data-content-grid>'+classifications.map(classificationCard).join("")+'</div><div data-content-empty hidden>'+intentionalEmpty("No hay coincidencias","Prueba otro término o restablece el filtro.")+'</div>'+intentionalEmpty("Las fichas se incorporarán progresivamente","Puedes recorrer desde ahora la estructura de clasificación y sus categorías.")}

export async function classificationNavigation(classificationSlug,categorySlugs=[]){const data=await api.getCategoryNavigation(classificationSlug,categorySlugs);if(!data)return statePage("Ruta de clasificación no encontrada","404","La clasificación o categoría solicitada no existe.");const {classification,current,trail,children}=data;const title=current?.name||classification.name;const description=current?.description||classification.description;const basePath="/informacion/"+classification.slug+(trail.length?"/"+trail.map(item=>item.slug).join("/"):"");const parentTrail=trail.slice(0,-1);const backFallback=parentTrail.length?"#/informacion/"+classification.slug+"/"+parentTrail.map(item=>item.slug).join("/"):"#/informacion";return '<button type="button" class="button ghost back-button" data-back-fallback="'+backFallback+'">← Volver</button>'+breadcrumbs(classification,trail)+header(classification.name,title,description)+(children.length?'<section class="section-intro"><span class="eyebrow">Explora los principales grupos</span><h2>'+children.length+' categorías en este nivel</h2></section><div class="content-grid hierarchy-grid">'+children.map(item=>categoryCard(item,basePath)).join("")+'</div>':intentionalEmpty("Las fichas de este grupo se incorporarán progresivamente","La ruta está preparada. No añadimos especies de ejemplo para rellenarla.","0 fichas publicadas en este grupo"))}

export async function speciesDetail(id){const species=await api.getSpecies(id);if(!species)return statePage("Ficha aún no publicada","Contenido pendiente","Las primeras fichas aparecerán cuando exista información revisada y fuentes verificadas.");return statePage(species.commonName,"Ficha informativa",species.summary)}
export async function ourWork(){const projects=await api.getOfficialProjects();return header("Proyectos de Los Más Buscados","Nuestro trabajo","Documentación de procesos realizados directamente por Los Más Buscados, independiente de las publicaciones de usuarios.",'<span class="official-label">Contenido oficial de Los Más Buscados</span>')+'<section class="principles-grid"><article class="card principle"><span>01</span><h2>Documentar</h2><p>Registro por etapas, observaciones, fotografías y actualizaciones.</p></article><article class="card principle"><span>02</span><h2>Relacionar</h2><p>Conexiones con fichas informativas sin duplicar conocimiento.</p></article><article class="card principle"><span>03</span><h2>Compartir</h2><p>Resultados solo cuando exista trabajo real que comunicar.</p></article></section>'+(projects.length?'<div class="project-grid">'+projects.map(p=>'<a class="card project-card" href="#/nuestro-trabajo/'+p.slug+'"><h2>'+p.title+'</h2></a>').join("")+'</div>':intentionalEmpty("Todavía no hay proyectos oficiales publicados","Este espacio no reutiliza publicaciones de usuarios.","0 proyectos publicados"))}
export async function projectDetail(id){const project=await api.getOfficialProject(id);if(!project)return statePage("Proyecto aún no publicado","Nuestro trabajo","No se inventaron proyectos, avances ni resultados.");return statePage(project.title,project.status,project.description)}
