import {editorialLibrary,editorialDetail} from './editorial.js';
import {api} from "../services/api.js";
import {header} from "../components/ui.js";
const icons={track:"◉",bird:"⌁",scale:"◇",drop:"◒",fish:"◁",wing:"⌘",spiral:"◎"};
const categoryCard=item=>'<article class="card category-card" data-content-card data-search="'+item.name.toLowerCase()+' '+item.description.toLowerCase()+'"><span class="nature-icon" aria-hidden="true">'+icons[item.icon]+'</span><div><span class="eyebrow">Categoría base</span><h2>'+item.name+'</h2><p>'+item.description+'</p><span class="structure-note">Subcategorías y fichas pendientes de contenido verificado</span></div></article>';
const emptyLibrary=(title,text)=>'<section class="card structured-empty"><span class="empty-orbit" aria-hidden="true">○</span><div><span class="eyebrow">Estructura disponible</span><h2>'+title+'</h2><p>'+text+'</p><span class="structure-note">No se añadieron especies ni datos científicos ficticios.</span></div></section>';
export async function uncommon(){const categories=await api.getTaxonomy();return header("Diversidad que merece espacio","Poco comunes","Una arquitectura abierta para organizar categorías, subcategorías, especies y fichas informativas sin reducir la vida animal a unas pocas opciones.",'<a class="button secondary" href="#/informacion">Explorar información y cuidados</a>')+'<section class="pathway" aria-label="Estructura de navegación"><span>Poco comunes</span><b aria-hidden="true">→</b><span>Categorías</span><b aria-hidden="true">→</b><span>Subcategorías</span><b aria-hidden="true">→</b><span>Especies</span><b aria-hidden="true">→</b><span>Ficha</span></section><div class="content-grid">'+categories.map(categoryCard).join("")+'</div>'+emptyLibrary("El catálogo crecerá con contenido real","Las fichas se activarán cuando existan categorías y fuentes definidas. La interfaz ya contempla jerarquía y relaciones.")}
export async function knowledge(){return editorialLibrary('article');}
export async function speciesDetail(id){return editorialDetail(id,'article');}
export async function ourWork(){return editorialLibrary('project');}
export async function projectDetail(id){return editorialDetail(id,'project');}
