/** Directorio, organización y perfil canónico del animal. */
import {api} from "../services/api.js";
import {header,statePage} from "../components/ui.js";
import {foundationAnimalCard} from "../components/foundation-animal-card.js";
const careLabels={underCare:"Bajo cuidado",recovering:"En recuperación",temporaryHome:"Hogar temporal",readyForHome:"Preparado para hogar"};
const adoptionLabels={notAvailable:"Adopción no disponible",available:"Disponible para adopción",inProcess:"Adopción en proceso",adopted:"Adoptado",temporarilyUnavailable:"Adopción pausada"};
const sponsorLabels={notAvailable:"Apadrinamiento no disponible",available:"Disponible para apadrinar",active:"Activo",paused:"Pausado",ended:"Finalizado"};
const demoBadge='<span class="demo-badge">Datos de demostración</span>';
const logo=item=>'<span class="foundation-logo" aria-hidden="true">'+item.name.split(" ").filter(x=>!["Demo","Organización"].includes(x)).slice(0,2).map(x=>x[0]).join("")+'</span>';

export async function foundationsPage(){const items=await api.getFoundations();return header("Organizaciones que cuidan","Fundaciones","Perfiles demostrativos de organizaciones y animales.")+'<section class="card library-tools foundation-tools"><div class="search"><label for="foundation-search">Buscar fundaciones</label><input id="foundation-search" class="input" data-foundation-search placeholder="Nombre, ubicación o tipo"></div><div class="field"><label for="foundation-filter">Disponibilidad</label><select id="foundation-filter" class="select" data-foundation-filter><option value="">Todas</option><option value="adoption">Con adopciones</option><option value="sponsorship">Con apadrinamientos</option></select></div></section><p class="caption" data-foundation-count>'+items.length+' fundación demo visible</p><div class="foundation-grid" data-foundation-grid>'+items.map(item=>'<article class="card foundation-card" data-foundation-card data-search="'+(item.name+" "+item.location+" "+item.animalTypes.join(" ")).toLowerCase()+'" data-adoption="'+item.adoptionCount+'" data-sponsorship="'+item.sponsorshipCount+'"><div class="foundation-card-head">'+logo(item)+'<div>'+demoBadge+'<h2>'+item.name+'</h2><span class="caption">'+item.location+'</span></div></div><p>'+item.description+'</p><div class="foundation-facts"><span><strong>'+item.adoptionCount+'</strong> en adopción</span><span><strong>'+item.sponsorshipCount+'</strong> para apadrinar</span></div><a class="button secondary block" href="#/fundaciones/'+item.slug+'">Ver fundación</a></article>').join("")+'</div><div data-foundation-empty hidden>'+statePage("Sin coincidencias","Filtros","No encontramos fundaciones con estos criterios.")+'</div>'}

export async function foundationProfile(slug){const item=await api.getFoundation(slug);if(!item)return statePage("Fundación no encontrada","404");const animals=await api.getFoundationAnimals(item.id);return '<button class="button ghost back-button" data-back-fallback="#/fundaciones">← Volver a Fundaciones</button><article class="card foundation-profile"><div class="foundation-cover"><img src="'+item.cover+'" alt="Portada demo de '+item.name+'"></div><div class="foundation-profile-body"><div class="foundation-identity">'+logo(item)+'<div>'+demoBadge+'<h1>'+item.name+'</h1><p>'+item.location+'</p></div></div><div class="foundation-profile-grid"><section><span class="eyebrow">Sobre la organización</span><h2>Descripción y misión</h2><p>'+item.description+'</p><p>'+item.mission+'</p></section><aside class="card contact-card"><h2>Contacto demo</h2><p>'+item.contact.email+'</p><span class="structure-note">No corresponde a una organización real.</span></aside></div></div></article><section class="section-intro"><span class="eyebrow">Individuos bajo su cuidado</span><h2>'+animals.length+' animales demo</h2></section><div class="foundation-animal-filter" role="group" aria-label="Filtrar animales"><button class="button secondary active" data-foundation-animal-filter="all" aria-pressed="true">Todos</button><button class="button secondary" data-foundation-animal-filter="adoption" aria-pressed="false">En adopción</button><button class="button secondary" data-foundation-animal-filter="sponsorship" aria-pressed="false">Para apadrinar</button></div><div class="foundation-animal-grid">'+animals.map(animal=>foundationAnimalCard(animal)).join("")+'</div>'}

export async function foundationAnimalProfile(slug){const animal=await api.getFoundationAnimal(slug);if(!animal)return statePage("Animal no encontrado","404","No existe un individuo asociado a esta ruta.");const foundation=await api.getFoundation(animal.foundationId);const canAdopt=animal.adoptionStatus==="available",canSponsor=animal.sponsorshipStatus==="available";return '<button class="button ghost back-button" data-back-fallback="#/fundaciones/'+foundation.slug+'">← Volver</button><article class="card animal-profile"><div class="animal-gallery"><img src="'+animal.images[0]+'" alt="'+animal.name+', bajo cuidado de '+foundation.name+'"></div><div class="animal-profile-copy">'+demoBadge+'<span class="eyebrow">Animal individual · no es ficha científica</span><h1>'+animal.name+'</h1><p>'+animal.description+'</p><a class="text-link animal-foundation-link" href="#/fundaciones/'+foundation.slug+'">Bajo el cuidado de '+foundation.name+' →</a><div class="details-list"><div><span>Referencia temporal</span><strong>'+animal.temporarySpeciesLabel+'</strong></div><div><span>Edad y sexo</span><strong>'+animal.estimatedAge+' · '+animal.sex+'</strong></div><div><span>Tamaño</span><strong>'+animal.size+'</strong></div><div><span>Estado</span><strong>'+careLabels[animal.careStatus]+'</strong></div><div><span>Necesidades especiales</span><strong>'+(animal.specialNeeds.length?animal.specialNeeds.join(", "):"Ninguna indicada")+'</strong></div><div><span>Ubicación</span><strong>'+animal.location+'</strong></div></div><section class="care-summary"><h2>Historia y salud</h2><p>'+animal.story+'</p><p>'+animal.healthSummary+'</p></section><div class="action-comparison"><div><strong>Adoptar</strong><p>Inicia una evaluación para un posible nuevo hogar.</p><button class="button secondary" '+(canAdopt?'data-adoption-demo':'disabled')+'>'+adoptionLabels[animal.adoptionStatus]+'</button></div><div><strong>Apadrinar</strong><p>Apoya mientras permanece bajo cuidado de la fundación.</p><button class="button" '+(canSponsor?'data-sponsorship-demo':'disabled')+'>'+sponsorLabels[animal.sponsorshipStatus]+'</button></div></div></div></article>'}

function openDemoDialog(content,label){const root=document.querySelector("#modal-root"),trigger=document.activeElement;root.innerHTML='<div class="modal-backdrop" data-dialog-backdrop><section class="modal sponsorship-modal" role="dialog" aria-modal="true" aria-labelledby="demo-dialog-title">'+content+'</section></div>';document.body.classList.add("modal-open");const close=()=>{document.removeEventListener("keydown",onKey);root.innerHTML="";document.body.classList.remove("modal-open");trigger?.focus()};const onKey=event=>{if(event.key==="Escape")close()};document.addEventListener("keydown",onKey);root.querySelectorAll("[data-close-dialog]").forEach(button=>button.addEventListener("click",close));root.querySelector("[data-dialog-backdrop]").addEventListener("click",event=>{if(event.target===event.currentTarget)close()});root.querySelector("button")?.focus();return label}
const modalShell=(title,body)=>'<header class="modal-head"><div><span class="eyebrow">Funcionalidad de demostración</span><h2 id="demo-dialog-title">'+title+'</h2></div><button class="icon-btn" data-close-dialog aria-label="Cerrar">×</button></header><div class="modal-body">'+body+'</div><footer class="modal-foot"><button class="button secondary" data-close-dialog>Entendido</button></footer>';
export function openAdoptionDemo(){return openDemoDialog(modalShell("Cómo funcionará la adopción",'<p>No se envía ninguna solicitud en esta demostración.</p><div class="demo-steps"><div class="demo-step"><div><h3>Conocer el perfil</h3><p>Revisar historia, cuidados y fundación responsable.</p></div></div><div class="demo-step"><div><h3>Enviar solicitud</h3><p>Una cuenta USER completará información pertinente.</p></div></div><div class="demo-step"><div><h3>Evaluación responsable</h3><p>La fundación revisará compatibilidad y podrá entrevistar.</p></div></div><div class="demo-step"><div><h3>Decisión y seguimiento</h3><p>La aprobación nunca será automática.</p></div></div></div><div class="demo-warning"><strong>Sin envío real</strong><span>No se guardan datos ni se contacta a la fundación.</span></div>'))}
export function openSponsorshipDemo(){return openDemoDialog(modalShell("Apadrinar no es adoptar",'<p>El apoyo futuro no concede propiedad y el animal continúa bajo responsabilidad de su fundación.</p><div class="demo-warning"><strong>No existe ningún pago</strong><span>No solicitamos tarjetas, datos bancarios ni montos.</span></div>'))}
