/** Modal demo. Los formularios de casos comparten Location y occurredAt, pero no persisten datos. */
import {api} from "../services/api.js";
import {locationSelectorMarkup,bindLocationSelector} from "./colombia-location-selector.js";
const today=()=>{const date=new Date(),pad=value=>String(value).padStart(2,"0");return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`};
const eventFields=(type)=>{const lost=type==="lost",label=lost?"Fecha en que se perdió":"Fecha en que fue encontrado";return locationSelectorMarkup(type)+`<fieldset class="event-time full"><legend>Momento del ${lost?"extravío":"hallazgo"}</legend><div class="field"><label for="${type}-date">${label}</label><input id="${type}-date" class="input" type="date" max="${today()}" required data-occurred-date></div><div class="field"><label for="${type}-time">Hora aproximada</label><input id="${type}-time" class="input" type="time" data-occurred-time><small>Déjala vacía si no la recuerdas.</small></div><label class="full"><input type="checkbox" data-approximate-time checked> La hora es aproximada o no se recuerda con exactitud</label></fieldset>`};
const fields={post:{title:"Crear publicación",intro:"Comparte una actualización con la comunidad.",extra:""},lost:{title:"Reportar animal perdido",intro:"Usa una ubicación aproximada útil; no publiques datos privados.",extra:'<div class="field"><label for="pet-name">Nombre</label><input id="pet-name" class="input" required></div>'+eventFields("lost")},found:{title:"Registrar animal encontrado",intro:"Indica dónde y cuándo ocurrió el hallazgo sin revelar una dirección privada.",extra:'<div class="field"><label for="species-modal">Especie</label><select id="species-modal" class="select"><option>Perro</option><option>Gato</option></select></div>'+eventFields("found")},claim:{title:"Reclamación de propiedad",intro:"La información permitirá verificar la reclamación.",extra:'<div class="field"><label for="old-name">Nombre que tenía</label><input id="old-name" class="input" required></div>'},"claim-family":{title:"Información sobre su familia",intro:"Comparte información privada que permita verificar a la familia.",extra:""}};

export function openModal(type){const f=fields[type]||fields.post,root=document.querySelector("#modal-root"),trigger=document.activeElement;root.innerHTML=`<div class="modal-backdrop" data-close-backdrop><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><div><span class="eyebrow">Formulario DEMO</span><h2 id="modal-title">${f.title}</h2></div><button class="icon-btn" data-close-modal aria-label="Cerrar">×</button></header><form data-demo-form><div class="modal-body"><p>${f.intro}</p><div class="form-grid">${f.extra}<div class="field full"><label for="description">Descripción</label><textarea id="description" class="textarea" maxlength="500" required></textarea><small>Máximo 500 caracteres</small></div></div></div><footer class="modal-foot"><button type="button" class="button secondary" data-close-modal>Cancelar</button><button class="button">Guardar borrador demo</button></footer></form></section></div>`;document.body.classList.add("modal-open");bindLocationSelector(root);bindModal(root,trigger)}
function bindModal(root,trigger){const esc=event=>{if(event.key==="Escape")close()},close=()=>{document.removeEventListener("keydown",esc);root.innerHTML="";document.body.classList.remove("modal-open");trigger?.focus()};root.querySelectorAll("[data-close-modal]").forEach(button=>button.addEventListener("click",close));root.querySelector("[data-close-backdrop]").addEventListener("click",event=>{if(event.target===event.currentTarget)close()});document.addEventListener("keydown",esc);root.querySelector("button,input,select,textarea")?.focus();root.querySelector("form").addEventListener("submit",async event=>{event.preventDefault();const date=root.querySelector("[data-occurred-date]");if(date&&date.value>today()){date.setCustomValidity("La fecha del evento no puede estar en el futuro.");date.reportValidity();return}const button=event.submitter;button.disabled=true;button.textContent="Guardando...";await api.submitDemo();close();toast("Borrador visual validado. No se enviaron datos.")})}
export function toast(message){const root=document.querySelector("#toast-root"),item=document.createElement("div");item.className="toast";item.textContent=message;root.append(item);setTimeout(()=>item.remove(),3500)}
