import {escapeHTML as e} from './ui.js';
import {icon} from './icons.js';
export function socialCase(p){
 const route='#/mascota/'+encodeURIComponent(p.id),resolved=p.state==='resolved'||p.state==='adopted',label=p.kind==='adoption'?p.status:resolved?'Caso resuelto':p.kind==='lost'?'Se busca a su familia':'Mascota encontrada';
 return `<article class="card case-post"><header class="case-post-head"><span class="case-avatar ${resolved?'resolved':p.kind}">${icon(resolved?'heart':'paw')}</span><div><strong>${p.kind==='adoption'?'Mascota en adopción':p.kind==='lost'?'Mascota perdida':'Mascota encontrada'}</strong><span>${e(p.city)}${p.time?' · '+e(p.time):''}</span></div><span class="badge ${resolved?'success':p.kind}">${e(p.status)}</span></header><div class="case-post-copy"><a href="${route}"><h2>${e(p.name)}</h2></a><p>${e(p.description)}</p></div><a class="case-post-photo ${p.image?'':'no-photo'}" href="${route}" aria-label="Ver el caso de ${e(p.name)}">${p.image?`<img src="${e(p.image)}" alt="${e(p.name)} · ${e(p.species)}" loading="lazy" decoding="async">`:`<span>${icon('paw',64)}<small>Fotografía aún no disponible</small></span>`}<span class="photo-location">${icon('pin',15)}${e([p.zone,p.city].filter(Boolean).join(', '))}</span></a><div class="case-post-meta"><span>${icon('paw',16)} ${e(p.species)}${p.color?' · '+e(p.color):''}</span><span>${label}</span></div><footer class="case-post-actions"><a href="${route}">${icon('message',19)}${p.canEdit?'Ver mi caso':'Tengo información'}</a><button type="button" data-share-case="${e(p.id)}" data-share-name="${e(p.name)}">${icon('share',19)}Compartir</button></footer><div class="demo-comments"><a href="${route}">${Number(p.commentCount)||0} comentarios</a></div></article>`;
}
export function socialContext(){return `<section class="card reunion-card"><span class="round-icon">${icon('heart',26)}</span><span class="eyebrow">Cada pista cuenta</span><h2>Alguien está esperando<br>que vuelva a casa.</h2><p>Una foto clara y una zona aproximada pueden acercar un reencuentro.</p><button class="button" data-modal="lost">${icon('plus',18)}Publicar un caso</button></section><section class="card community-guide"><h2>Ayuda de forma segura</h2><div>${icon('image')}<p><strong>Una foto que lo identifique</strong><span>Muestra su rostro y sus marcas especiales.</span></p></div><div>${icon('pin')}<p><strong>Una ubicación aproximada</strong><span>Comparte el barrio, sin tu dirección personal.</span></p></div><div>${icon('shield')}<p><strong>Conversaciones privadas</strong><span>Intercambia detalles desde el caso.</span></p></div></section><div class="community-footer"><span>Buscados · Juntos, de vuelta a casa.</span><a href="#/informacion">Información y cuidados ${icon('arrow',14)}</a></div>`;}
export function bindSharing(){document.querySelectorAll('[data-share-case]').forEach(button=>button.addEventListener('click',async()=>{
 const url=location.origin+'/#/mascota/'+encodeURIComponent(button.dataset.shareCase),title='Ayudemos a '+button.dataset.shareName;
 try{if(navigator.share)await navigator.share({title,url});else{await navigator.clipboard.writeText(url);button.innerHTML=icon('check',19)+'Enlace copiado';}}catch(error){if(error.name!=='AbortError'){const field=document.createElement('input');field.className='input';field.value=url;field.readOnly=true;field.setAttribute('aria-label','Enlace del caso para copiar');button.replaceWith(field);field.select();}}
}));}
