const tone={lost:"lost",found:"found",adoption:"adoption",success:"success"};
export const header=(eyebrow,title,text,action="")=>`<header class="page-header"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>${action}</header>`;
export const escapeHTML=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
export const petCard=(p,options={})=>{
  const e=escapeHTML, name=p.name||p.species||"Ver caso";
  const location=[p.zone,p.city].filter(Boolean).join(" · ");
  return `<article class="card pet-card" data-kind="${e(p.kind)}" data-search="${e([p.name,p.species,p.breed,p.city,p.zone,p.size].filter(Boolean).join(" "))}" data-city="${e(p.city)}" data-species="${e(p.species)}" data-size="${e(p.size)}"><a href="#/mascota/${encodeURIComponent(p.id)}${options.from?'?from='+encodeURIComponent(options.from):''}" class="pet-card-link"><div class="pet-card-image">${p.image?`<img src="${e(p.image)}" alt="${e([p.name,p.species,p.color].filter(Boolean).join(", "))}" loading="lazy" decoding="async">`:'<span class="pet-no-photo">Sin fotografía</span>'}${p.status?`<span class="badge ${p.state==='resolved'?'success':tone[p.kind]||""}">${p.state==='resolved'?'✓ Caso resuelto':e(p.status)}</span>`:""}</div><div class="pet-card-body"><h2>${e(name)}</h2>${p.visibility==="hidden"?'<span class="badge">Oculto por moderación</span>':""}${location?`<span class="caption pet-location">${e(location)}</span>`:""}<div class="pet-facts">${[p.species,p.color,p.size,p.sex].filter(Boolean).map(value=>`<span class="fact">${e(value)}</span>`).join("")}</div>${p.description?`<p class="pet-summary">${e(p.description)}</p>`:""}<div class="pet-card-footer">${p.time?`<span class="caption">${e(p.time)}</span>`:""}<strong>Ver caso →</strong></div></div></a></article>`;
};
export const postCard=p=>`<article class="card post"><header class="post-head"><img src="${p.avatar}" alt=""><div class="post-author"><strong>${p.author} ${p.verified?'<span class="verified" title="Organización verificada">●</span>':''}</strong><span>${p.handle} · ${p.time}</span></div><button class="icon-btn" aria-label="Más opciones">•••</button></header><div class="post-body"><p>${p.text}</p></div><div class="post-media"><img src="${p.image}" alt="Fotografía relacionada con ${p.status.toLowerCase()}" loading="lazy"><span class="post-status badge ${tone[p.type]||''}">${p.status}</span></div><div class="post-meta"><span>⌖ ${p.location}</span><span>${p.supports} apoyos</span><span>${p.comments} comentarios</span></div><footer class="post-actions"><button data-support>♡ <span>Apoyar</span></button><button data-demo="Los comentarios se conectarán en la siguiente etapa.">○ <span>Comentar</span></button><button data-demo="La función de compartir se habilitará más adelante.">↗ <span>Compartir</span></button><button data-demo="Guardado preparado para una fase posterior.">□ <span>Guardar</span></button></footer></article>`;
export const filters=(kind='')=>{
 const select=(name,label,options)=>`<label for="filter-${name}">${label}<select id="filter-${name}" class="select" data-case-filter="${name}">${options.map(([value,text])=>`<option value="${value}">${text}</option>`).join('')}</select></label>`;
 const text=(name,label)=>`<label for="filter-${name}">${label}<input id="filter-${name}" class="input" maxlength="120" data-case-filter="${name}"></label>`;
 return `<section class="card filters-panel" data-case-filters><div class="search full"><label for="pet-search">Buscar por nombre, especie, raza, color, ubicación o descripción</label><input id="pet-search" class="input" maxlength="100" placeholder="Ej. gato negro, Bogotá" data-search-input></div><details class="case-filter-details"><summary>Filtros <span data-filter-count></span></summary><div class="case-filter-fields">${!kind?select('kind','Tipo de reporte',[['','Todos'],['lost','Perdido'],['found','Encontrado']]):''}${kind!=='adoption'?select('state','Situación',[['','Todas'],['open','Abierto'],['resolved','Resuelto']]):''}${select('species','Especie',[['','Todas'],['Perro','Perro'],['Gato','Gato'],['Ave','Ave'],['Otro','Otro']])}${select('sex','Sexo',[['','Todos'],['Macho','Macho'],['Hembra','Hembra']])}${select('size','Tamaño',[['','Todos'],['Pequeño','Pequeño'],['Mediano','Mediano'],['Grande','Grande']])}${text('color','Color')}${text('city','Ciudad')}${text('zone','Barrio o zona')}${select('period','Fecha de publicación',[['','Todas'],['today','Hoy (Colombia)'],['7','Últimos 7 días'],['30','Últimos 30 días']])}</div></details><div class="case-search-actions">${select('sort','Ordenar',[['','Más recientes'],['oldest','Más antiguos'],['relevance','Relevancia del texto']])}<button type="button" class="button secondary" data-clear-filters>Limpiar filtros</button></div></section><p class="caption" data-results-count role="status" aria-live="polite" aria-atomic="true"></p>`;
};
export const statePage=(title,label="Próximamente",text="Esta sección está preparada en la navegación, pero todavía no implementa una funcionalidad real.")=>`${header("Hoja de ruta",title,text)}<section class="card state-card"><div class="state-symbol">◇</div><span class="badge">${label}</span><h2>Estamos preparando este espacio</h2><p>${text}</p><a class="button secondary" href="#/inicio">Volver al inicio</a></section>`;
export function contextFor(route){const maps={"/inicio":["Consejo de seguridad","Nunca publiques una dirección exacta. Comparte una zona aproximada.","Actividad cercana","Explora los reportes publicados por la comunidad."],"/perdidos":["Primeras 24 horas","Busca en silencio, revisa cámaras cercanas y actualiza el reporte.","Casos recientes","Consulta los reportes más recientes en el listado."],"/encontrados":["Verificación segura","Conserva detalles privados para validar a quien reclame.","Privacidad","La evidencia nunca se muestra en el feed."],"/adopciones":["Adopción responsable","Una solicitud inicia una evaluación, no una reserva ni una compra.","Antes de solicitar","Evalúa tiempo, espacio y compromiso a largo plazo."],"/veterinarias":["Antes de acudir","Confirma horarios y disponibilidad directamente con el establecimiento.","Fuente y fecha","Cada ficha publicada muestra la fuente y la fecha de comprobación de sus datos."]};const m=maps[route]||maps["/inicio"];return `<section class="card context-card notice"><span class="eyebrow">Información útil</span><h2>${m[0]}</h2><p>${m[1]}</p></section><section class="card context-card"><h2>${m[2]}</h2><p>${m[3]}</p></section><section class="card context-card"><h2>¿Necesitas ayuda?</h2><div class="context-list"><div class="context-item"><span class="mini-icon">!</span><div><strong>Reportar perdida</strong><span>Inicia un caso con información clara.</span></div></div><div class="context-item"><span class="mini-icon">✓</span><div><strong>Animal encontrado</strong><span>Protégelo mientras buscamos a su familia.</span></div></div></div></section>`}
export const loading=()=>`<div class="card state-card"><div class="state-symbol">…</div><h2>Cargando información</h2><p>Estamos preparando la información.</p></div>`;
export const empty=(text)=>`<div class="card state-card"><div class="state-symbol">⌕</div><h2>Sin resultados</h2><p>${text}</p></div>`;
