/** Componentes HTML puros; convierten datos demo en tarjetas y estados reutilizables. */
import { caseLocationFiltersMarkup, findDepartment, findMunicipality } from "./colombia-location-selector.js";
const tone = { lost: "lost", found: "found", adoption: "adoption", success: "success" };
export const formatDateCO = value => new Intl.DateTimeFormat("es-CO", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(value + "T00:00:00Z"));
export const formatOccurredTime = occurredAt => occurredAt.time ? occurredAt.time + (occurredAt.approximateTime ? " aprox." : "") : "Hora desconocida";
export const locationNames = location => ({ department: findDepartment(location?.departmentId)?.name || "Departamento no disponible", municipality: findMunicipality(location?.municipalityId)?.name || "Municipio no disponible" });
export const header = (eyebrow, title, text, action = "") => `<header class="page-header"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>${action}</header>`;
export const petCard = p => { const names = locationNames(p.location), where = p.location ? `${names.municipality}, ${names.department}` : `${p.city}`; const search = [p.name, p.species, p.breed, p.zone, where, p.location?.placeDescription || "", p.location?.departmentId || "", p.location?.municipalityId || ""].join(" "); return `<article class="card pet-card" data-kind="${p.kind}" data-search="${search}" data-department="${p.location?.departmentId || ""}" data-municipality="${p.location?.municipalityId || ""}"><a href="#/mascota/${p.id}" class="pet-card-image"><img src="${p.image}" alt="${p.name}, ${p.species.toLowerCase()} ${p.color.toLowerCase()}" loading="lazy"><span class="badge ${tone[p.kind]}">${p.status}</span></a><div class="pet-card-body"><h2>${p.name}</h2><span class="caption">${where}${p.location?.placeDescription ? ` · ${p.location.placeDescription}` : ""}</span><div class="pet-facts"><span class="fact">${p.species}</span><span class="fact">${p.size}</span><span class="fact">${p.sex}</span></div><p>${p.description}</p><div class="pet-card-footer"><span class="caption">${p.occurredAt ? formatDateCO(p.occurredAt.date) : p.time}</span><a href="#/mascota/${p.id}"><strong>Ver caso →</strong></a></div></div></article>` };
export const postCard = p => `<article class="card post"><header class="post-head"><img src="${p.avatar}" alt=""><div class="post-author"><strong>${p.author}</strong><span>${p.handle} · ${p.time}</span></div></header><div class="post-body"><p>${p.text}</p></div><div class="post-media"><img src="${p.image}" alt="Fotografía relacionada con ${p.status.toLowerCase()}" loading="lazy"><span class="post-status badge ${tone[p.type] || ""}">${p.status}</span></div><div class="post-meta"><span>${p.location}</span><span>${p.supports} apoyos</span></div><footer class="post-actions"><button data-support>♡ <span>Apoyar</span></button><button data-demo="Comentarios disponibles en una fase posterior.">Comentar</button></footer></article>`;
export const filters = kind => `<section class="card filters-panel" aria-label="Filtros"><div class="search"><label for="pet-search">Buscar</label><input id="pet-search" class="input" placeholder="Nombre, municipio o lugar" data-search-input></div>${["animales perdidos", "animales encontrados"].includes(kind) ? caseLocationFiltersMarkup() : ""}<div class="field"><label for="species">Especie</label><select id="species" class="select" data-filter="species"><option value="">Todas</option><option>Perro</option><option>Gato</option></select></div><div class="field"><label for="size">Tamaño</label><select id="size" class="select" data-filter="size"><option value="">Todos</option><option>Pequeño</option><option>Mediano</option><option>Mediana</option><option>Grande</option></select></div></section><p class="caption" data-results-count>Mostrando resultados demo de ${kind}.</p>`;
export const statePage = (title, label = "Próximamente", text = "Esta sección todavía no implementa funcionalidad real.") => `${header("Hoja de ruta", title, text)}<section class="card state-card"><div class="state-symbol">◇</div><span class="badge">${label}</span><h2>Estamos preparando este espacio</h2><p>${text}</p><a class="button secondary" href="#/inicio">Volver al inicio</a></section>`;
export function contextFor(route) { const maps = { "/inicio": ["Consejo de seguridad", "Nunca publiques una dirección exacta.", "Actividad cercana", "Datos completamente demostrativos."], "/perdidos": ["Primeras 24 horas", "Comparte municipio y un punto de referencia aproximado.", "Privacidad", "No publiques domicilios ni coordenadas exactas."], "/encontrados": ["Verificación segura", "Conserva detalles privados para validar a la familia.", "Momento del hallazgo", "La fecha del evento es distinta a la publicación."], "/adopciones": ["Adopción responsable", "Una solicitud inicia una evaluación.", "Antes de solicitar", "Evalúa el compromiso a largo plazo."] }; const m = maps[route] || maps["/inicio"]; return `<section class="card context-card notice"><span class="eyebrow">Información útil</span><h2>${m[0]}</h2><p>${m[1]}</p></section><section class="card context-card"><h2>${m[2]}</h2><p>${m[3]}</p></section>` }
export const loading = () => `<div class="card state-card"><h2>Cargando información</h2><p>Estamos preparando los datos demo.</p></div>`;
export const empty = text => `<div class="card state-card"><h2>Sin resultados</h2><p>${text}</p></div>`;
