/** Controlador SPA: rutas, sesión demo y enlaces de interacción. */
import "./history-state.js";
import {APP_CONFIG,navItems} from "./config.js";import {api} from "./services/api.js";
import {home,listing} from "./pages/core.js";import {detail} from "./pages/detail.js";import {explore,veterinaries,profile,notificationsPage} from "./pages/more.js";
import {uncommon,knowledge,classificationNavigation,speciesDetail,ourWork,projectDetail} from "./pages/discovery.js";
import {foundationsPage,foundationProfile,foundationAnimalProfile,openSponsorshipDemo,openAdoptionDemo} from "./pages/foundations.js";import {adoptionsPage} from "./pages/adoptions.js";
import {login,register,recovery} from "./pages/auth.js";import {bindCaseLocationFilters} from "./components/colombia-location-selector.js";import {statePage,contextFor,loading,petCard} from "./components/ui.js";import {openModal,toast} from "./components/modal.js";import {getDemoRole,renderSessionUI} from "./components/session-menu.js";
for(const href of ["frontend/css/pages.css","frontend/css/review.css","frontend/css/hierarchy.css","frontend/css/foundations.css","frontend/css/adoptions.css","frontend/css/locations.css"]){const style=document.createElement("link");style.rel="stylesheet";style.href=href;document.head.append(style)}
const root=document.querySelector("#page-root"),context=document.querySelector("#context-panel"),sidebar=document.querySelector(".sidebar");document.querySelectorAll("[data-brand-name]").forEach(el=>el.textContent=APP_CONFIG.brand.name);
const currentPath=()=>location.hash.replace(/^#/,"").split("?")[0]||"/inicio";const privateRoutes=new Set(["/perfil","/publicaciones","/casos","/apadrinamientos","/solicitudes-adopcion","/notificaciones","/configuracion"]);
function renderNav(){const role=getDemoRole(),visible=navItems.filter(item=>!(role==="PUBLIC"&&item.private));document.querySelector("#main-nav").innerHTML=visible.map(item=>item.group?'<span class="nav-group">'+item.group+'</span>':'<a class="nav-link" href="#'+item.route+'" data-route="'+item.route+'"><span class="symbol">'+item.icon+'</span><span>'+item.label+'</span>'+(item.soon?'<small class="soon">'+item.soon+'</small>':"")+'</a>').join("");const mobileRoutes=["/inicio","/perdidos","/poco-comunes","/informacion",role==="PUBLIC"?"/login":"/perfil"];document.querySelector("#mobile-nav").innerHTML=visible.filter(item=>item.route&&mobileRoutes.includes(item.route)).map(item=>'<a class="nav-link" href="#'+item.route+'" data-route="'+item.route+'"><span class="symbol">'+item.icon+'</span><span>'+item.label+'</span></a>').join("")}
async function render(){const path=currentPath(),role=getDemoRole();renderNav();if(role==="PUBLIC"&&privateRoutes.has(path)){location.hash="#/login";return}if(path.startsWith("/fundaciones/animal/")){location.replace("#/animales/"+path.split("/").pop());return}root.innerHTML=loading();context.innerHTML=contextFor(path);document.querySelectorAll("[data-route]").forEach(a=>{const active=path===a.dataset.route;a.classList.toggle("active",active);if(active)a.setAttribute("aria-current","page");else a.removeAttribute("aria-current")});sidebar.classList.remove("open");let content;
 if(path==="/inicio")content=await home();else if(path==="/explorar")content=await explore();else if(path==="/perdidos")content=await listing("lost");else if(path==="/encontrados")content=await listing("found");else if(path==="/adopciones")content=await adoptionsPage();
 else if(path.startsWith("/animales/"))content=await foundationAnimalProfile(path.split("/").pop());else if(path==="/fundaciones")content=await foundationsPage();else if(path.startsWith("/fundaciones/"))content=await foundationProfile(path.split("/").pop());
 else if(path==="/poco-comunes")content=await uncommon();else if(path==="/informacion")content=await knowledge();else if(path.startsWith("/informacion/especie/"))content=await speciesDetail(path.split("/").pop());else if(path.startsWith("/informacion/")){const parts=path.split("/").filter(Boolean);content=await classificationNavigation(parts[1],parts.slice(2))}else if(path==="/nuestro-trabajo")content=await ourWork();else if(path.startsWith("/nuestro-trabajo/"))content=await projectDetail(path.split("/").pop());else if(path==="/veterinarias")content=await veterinaries();
 else if(path==="/perfil")content=await profile();else if(path==="/publicaciones")content=await profile("publications");else if(path==="/casos")content=await profile("cases");else if(path==="/apadrinamientos")content=await profile("sponsorships");else if(path==="/solicitudes-adopcion")content=await profile("adoptions");else if(path==="/notificaciones")content=await notificationsPage();
 else if(["/mensajes","/donaciones","/tienda","/minijuegos","/gps"].includes(path)){const labels={"/mensajes":"Mensajes","/donaciones":"Donaciones","/tienda":"Tienda","/minijuegos":"Minijuegos","/gps":"Localización GPS"};content=statePage(labels[path],"Próximamente")}else if(path==="/login")content=login();else if(path==="/registro")content=register();else if(path==="/recuperar")content=recovery();else if(path==="/configuracion")content=statePage("Configuración","Demo","Las preferencias se conectarán a FastAPI.");else if(path.startsWith("/mascota/"))content=await detail(path.split("/").pop());else content=statePage("Página no encontrada","404","La ruta solicitada no existe.");root.innerHTML=content;bindPage();document.querySelector("#main-content").focus({preventScroll:true});window.scrollTo({top:0,behavior:"instant"})}
function smartBack(button){if(window.__nexoNavigationCount>0)history.back();else location.href=button.dataset.backFallback||"#/inicio"}
function bindPage(){root.querySelectorAll("[data-modal]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.modal)));root.querySelectorAll("[data-demo]").forEach(b=>b.addEventListener("click",()=>toast(b.dataset.demo)));root.querySelectorAll("[data-back-fallback]").forEach(b=>b.addEventListener("click",()=>smartBack(b)));root.querySelectorAll("[data-sponsorship-demo]").forEach(b=>b.addEventListener("click",openSponsorshipDemo));root.querySelectorAll("[data-adoption-demo]").forEach(b=>b.addEventListener("click",openAdoptionDemo));root.querySelectorAll("[data-support]").forEach(b=>b.addEventListener("click",()=>{b.classList.toggle("active");b.textContent=b.classList.contains("active")?"Apoyado":"Apoyar"}));root.querySelector("[data-read-all]")?.addEventListener("click",()=>{root.querySelectorAll(".notification").forEach(n=>n.classList.remove("unread"));toast("Notificaciones leídas.")});root.querySelector("[data-auth-form]")?.addEventListener("submit",e=>{e.preventDefault();toast("Validación demo correcta.")});bindFilters();bindGlobal();bindContentFilters();bindFoundationFilters();bindAdoptionFilters();bindFoundationAnimalFilters()}
function bindPersistentActions(){document.querySelectorAll(".sidebar-actions [data-modal]").forEach(b=>b.addEventListener("click",()=>openModal(b.dataset.modal)))}
function bindFilters(){const search=root.querySelector("[data-search-input]"),selects=[...root.querySelectorAll("[data-filter]")];if(!search)return;const update=()=>{const q=search.value.toLowerCase(),values=selects.map(s=>s.value).filter(Boolean);let visible=0;root.querySelectorAll(".pet-card").forEach(card=>{const match=card.dataset.search.toLowerCase().includes(q)&&values.every(v=>card.dataset.search.includes(v));card.hidden=!match;if(match)visible++});root.querySelector("[data-results-count]").textContent=visible+" resultados encontrados.";root.querySelector("[data-empty-results]").hidden=visible>0};bindCaseLocationFilters(root,update);search.addEventListener("input",update);selects.forEach(s=>s.addEventListener("change",update))}
function bindAdoptionFilters(){const search=root.querySelector("[data-adoption-search]"),filters=[...root.querySelectorAll("[data-adoption-filter]")];if(!search)return;const update=()=>{let visible=0;root.querySelectorAll("[data-adoption-card]").forEach(card=>{const match=card.dataset.search.includes(search.value.trim().toLowerCase())&&filters.every(filter=>!filter.value||card.dataset[filter.dataset.adoptionFilter]===filter.value);card.hidden=!match;if(match)visible++});root.querySelector("[data-adoption-count]").textContent=visible+" animales disponibles";root.querySelector("[data-adoption-empty]").hidden=visible>0};search.addEventListener("input",update);filters.forEach(filter=>filter.addEventListener("change",update))}
function bindFoundationAnimalFilters(){root.querySelectorAll("[data-foundation-animal-filter]").forEach(button=>button.addEventListener("click",()=>{const value=button.dataset.foundationAnimalFilter;root.querySelectorAll("[data-foundation-animal-filter]").forEach(item=>{item.classList.toggle("active",item===button);item.setAttribute("aria-pressed",String(item===button))});root.querySelectorAll("[data-adoption-card]").forEach(card=>{const slug=card.querySelector("a")?.hash.split("/").pop();api.getFoundationAnimal(slug).then(animal=>card.hidden=value==="adoption"?animal.adoptionStatus!=="available":value==="sponsorship"?animal.sponsorshipStatus!=="available":false)})}))}
function bindContentFilters(){const search=root.querySelector("[data-content-search]"),filter=root.querySelector("[data-content-filter]");if(!search)return;const update=()=>{const query=search.value.trim().toLowerCase(),classification=filter.value;let visible=0;root.querySelectorAll("[data-content-card]").forEach(card=>{const match=card.dataset.search.includes(query)&&(!classification||card.dataset.search.includes(classification));card.hidden=!match;if(match)visible++});root.querySelector("[data-content-empty]").hidden=visible>0;root.querySelector("[data-content-count]").textContent=visible+" clasificaciones visibles · 0 fichas publicadas"};search.addEventListener("input",update);filter.addEventListener("change",update)}
function bindFoundationFilters(){const search=root.querySelector("[data-foundation-search]"),filter=root.querySelector("[data-foundation-filter]");if(!search)return;const update=()=>{let visible=0;root.querySelectorAll("[data-foundation-card]").forEach(card=>{const match=card.dataset.search.includes(search.value.trim().toLowerCase())&&(!filter.value||Number(card.dataset[filter.value])>0);card.hidden=!match;if(match)visible++});root.querySelector("[data-foundation-count]").textContent=visible+" fundaciones demo visibles";root.querySelector("[data-foundation-empty]").hidden=visible>0};search.addEventListener("input",update);filter.addEventListener("change",update)}
function bindGlobal(){const input=root.querySelector("[data-global-search]");input?.addEventListener("input",async()=>{const items=await api.search(input.value);root.querySelector("[data-search-results]").innerHTML=items.length?items.map(petCard).join(""):'<div class="card state-card"><h2>Sin resultados</h2></div>'})}
function refreshSession(){renderSessionUI(()=>{renderNav();const path=currentPath();if(getDemoRole()==="PUBLIC"&&privateRoutes.has(path))location.hash="#/inicio";else render()})}
refreshSession();renderNav();bindPersistentActions();document.querySelector("[data-mobile-menu]").addEventListener("click",e=>{sidebar.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",sidebar.classList.contains("open"))});window.addEventListener("hashchange",render);render();
